annotation-processor-common/src/main/java/ru/tinkoff/kora/annotation/processor/common/CommonUtils.java, annotation-processor-common/src/testFixtures/java/ru/tinkoff/kora/annotation/processor/common/TestUtils.java, build.gradle, database/database-jdbc/src/main/java/ru/tinkoff/kora/database/jdbc/JdbcModule.java, json/json-annotation-processor/src/main/java/ru/tinkoff/kora/json/annotation/processor/JsonAnnotationProcessor.java, json/json-annotation-processor/src/main/java/ru/tinkoff/kora/json/annotation/processor/writer/SealedInterfaceWriterGenerator.java, json/json-common/src/main/java/ru/tinkoff/kora/json/common/annotation/Json.java, json/json-module/build.gradle, json/json-module/src/main/java/ru/tinkoff/kora/json/module/JsonModule.java, json/json-symbol-processor/src/main/kotlin/ru/tinkoff/kora/json/ksp/reader/JsonReaderGenerator.kt, json/json-symbol-processor/src/main/kotlin/ru/tinkoff/kora/json/ksp/writer/SealedInterfaceWriterGenerator.kt, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/GraphBuilder.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/GraphResolutionHelper.java, kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/GraphBuilder.kt, kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/GraphResolutionHelper.kt, logging/logging-logback/src/main/java/ru/tinkoff/kora/logging/logback/KoraAsyncAppender.java, openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java, openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaAnnotatedParams.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaClientResponseMappers.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaServerResponseMappers.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinAnnotatedParams.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinClientApi.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinClientResponseMappers.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinServerApi.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinServerResponseMappers.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/reactiveClientApi.mustache, symbol-processor-common/src/main/kotlin/ru/tinkoff/kora/ksp/common/KspCommonUtils.kt
- `@Json` tag support
- `null` value case in sealed type json writer fix
- npe for null values in mdc fix
- template component resolving for multiple matching declaration
=> Pre 0.10.0 fixes

database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/vertx/VertxRepositoryGenerator.kt, database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/vertx/VertxParametersTest.kt
Repository should generate correct queries now.
=> VertxRepository sql processing fix

annotation-processor-common/build.gradle, annotation-processor-common/src/testFixtures/java/ru/tinkoff/kora/annotation/processor/common/AbstractAnnotationProcessorTest.java, annotation-processor-common/src/testFixtures/java/ru/tinkoff/kora/annotation/processor/common/CompileResult.java, annotation-processor-common/src/testFixtures/java/ru/tinkoff/kora/annotation/processor/common/compile/ByteArrayJavaFileObject.java, annotation-processor-common/src/testFixtures/java/ru/tinkoff/kora/annotation/processor/common/compile/InTestGeneratedJavaFileObject.java, annotation-processor-common/src/testFixtures/java/ru/tinkoff/kora/annotation/processor/common/compile/KoraCompileTestJavaClassLoader.java, annotation-processor-common/src/testFixtures/java/ru/tinkoff/kora/annotation/processor/common/compile/KoraCompileTestJavaFileManager.java, dependencies.gradle, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/GraphBuilder.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/GraphResolutionHelper.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/KoraAppProcessor.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/component/ComponentDependency.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/component/ComponentDependencyHelper.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/component/DependencyClaim.java, kora-app-annotation-processor/src/test/java/ru/tinkoff/kora/kora/app/annotation/processor/AbstractKoraAppTest.java, kora-app-annotation-processor/src/test/java/ru/tinkoff/kora/kora/app/annotation/processor/DependencyTest.java
=> New annotation processing test classes

json/json-annotation-processor/src/main/java/ru/tinkoff/kora/json/annotation/processor/KnownType.java, json/json-annotation-processor/src/main/java/ru/tinkoff/kora/json/annotation/processor/reader/JsonReaderGenerator.java, json/json-annotation-processor/src/main/java/ru/tinkoff/kora/json/annotation/processor/writer/JsonWriterGenerator.java, json/json-annotation-processor/src/test/java/ru/tinkoff/kora/json/annotation/processor/JsonAnnotationProcessorTest.java, json/json-annotation-processor/src/test/java/ru/tinkoff/kora/json/annotation/processor/dto/DtoWithSupportedTypes.java, json/json-common/src/main/java/ru/tinkoff/kora/json/common/KoraDateTimeFormatters.java, json/json-symbol-processor/src/main/kotlin/ru/tinkoff/kora/json/ksp/KnownType.kt, json/json-symbol-processor/src/main/kotlin/ru/tinkoff/kora/json/ksp/reader/JsonReaderGenerator.kt, json/json-symbol-processor/src/main/kotlin/ru/tinkoff/kora/json/ksp/writer/JsonWriterGenerator.kt, json/json-symbol-processor/src/test/kotlin/ru/tinkoff/kora/json/ksp/JsonAnnotationProcessorTest.kt, json/json-symbol-processor/src/test/kotlin/ru/tinkoff/kora/json/ksp/dto/DtoWithSupportedTypes.kt
- Time types removed from native to inject JsonWriter or JsonReader fixed
=> Json Native Time types removed

.github/workflows/publish-release.yml, .github/workflows/publish-snapshot.yml
This reverts commit 8afc5a962a7121ea3c8679818e6aaf39d5f0abf6.
=> Revert "Change publishing to s01.oss.sonatype.org (#62)"

mkdocs/docs/features/resilient.md
Resilient Documentation more examples added and detailed description for features
=> resilient.md doc improved

kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/KoraAppProcessor.kt, kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/KoraAppProcessorProvider.kt, kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/component/ComponentDependencyHelper.kt, kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/declaration/ComponentDeclaration.kt, kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/interceptor/ComponentInterceptors.kt, kora-app-symbol-processor/src/test/kotlin/ru/tinkoff/kora/kora/app/ksp/InvalidTypeTest.kt
=> Make ksp errors about non-existing types a bit more verbose

cache/cache-annotation-processor/src/main/java/ru/tinkoff/kora/cache/annotation/processor/CacheKeyAnnotationProcessor.java, cache/cache-annotation-processor/src/main/java/ru/tinkoff/kora/cache/annotation/processor/CacheOperation.java, cache/cache-annotation-processor/src/main/java/ru/tinkoff/kora/cache/annotation/processor/aop/AbstractAopCacheAspect.java, cache/cache-symbol-processor/src/main/kotlin/ru/tinkoff/kora/cache/symbol/processor/aop/AbstractAopCacheAspect.kt
- Cache processor return true and next processor skips annotations fixed
- Cache processing error type fixed
=> Cache processing fixed

validation/validation-annotation-processor/src/main/java/ru/tinkoff/kora/validation/annotation/processor/ValidAnnotationProcessor.java, validation/validation-annotation-processor/src/main/java/ru/tinkoff/kora/validation/annotation/processor/aop/ValidateMethodKoraAspect.java, validation/validation-annotation-processor/src/test/java/ru/tinkoff/kora/validation/annotation/processor/ValidAnnotationProcessorTests.java, validation/validation-annotation-processor/src/test/java/ru/tinkoff/kora/validation/annotation/processor/ValidRunner.java, validation/validation-annotation-processor/src/test/java/ru/tinkoff/kora/validation/annotation/processor/ValidateAspectTests.java, validation/validation-annotation-processor/src/test/java/ru/tinkoff/kora/validation/annotation/processor/testdata/ValidBar.java, validation/validation-annotation-processor/src/test/java/ru/tinkoff/kora/validation/annotation/processor/testdata/ValidFoo.java, validation/validation-annotation-processor/src/test/java/ru/tinkoff/kora/validation/annotation/processor/testdata/ValidTaz.java, validation/validation-annotation-processor/src/test/java/ru/tinkoff/kora/validation/annotation/processor/testdata/ValidateFlux.java, validation/validation-annotation-processor/src/test/java/ru/tinkoff/kora/validation/annotation/processor/testdata/ValidateMono.java, validation/validation-annotation-processor/src/test/java/ru/tinkoff/kora/validation/annotation/processor/testdata/ValidateSync.java, validation/validation-symbol-processor/src/main/kotlin/ru/tinkoff/kora/validation/symbol/processor/ValidSymbolProcessor.kt, validation/validation-symbol-processor/src/test/kotlin/ru/tinkoff/kora/validation/symbol/processor/testdata/ValidBar.kt, validation/validation-symbol-processor/src/test/kotlin/ru/tinkoff/kora/validation/symbol/processor/testdata/ValidFoo.kt, validation/validation-symbol-processor/src/test/kotlin/ru/tinkoff/kora/validation/symbol/processor/testdata/ValidTaz.kt, validation/validation-symbol-processor/src/test/kotlin/ru/tinkoff/kora/validation/symbol/processor/testdata/ValidateFlow.kt, validation/validation-symbol-processor/src/test/kotlin/ru/tinkoff/kora/validation/symbol/processor/testdata/ValidateSuspend.kt, validation/validation-symbol-processor/src/test/kotlin/ru/tinkoff/kora/validation/symbol/processor/testdata/ValidateSync.kt
Features:
- Static fields ignored for Java
- Const and Static ignored for Kotlin
=> Validator bugfixes

mkdocs/docs/examples/hello-world.md, mkdocs/docs/features/http-server.md
=> Improve docs about json responses

database/database-cassandra/src/main/java/ru/tinkoff/kora/database/cassandra/CassandraConfig.java, database/database-cassandra/src/main/java/ru/tinkoff/kora/database/cassandra/CassandraSessionBuilder.java
[docs](https://docs.datastax.com/en/developer/java-driver/4.14/manual/core/throttling/)
=> Add throttler config to CassandraConfig

resilient/resilient-annotation-processor/src/main/java/ru/tinkoff/kora/resilient/annotation/processor/aop/CircuitBreakerKoraAspect.java, resilient/resilient-annotation-processor/src/test/java/ru/tinkoff/kora/resilient/annotation/processor/aop/CircuitBreakerTests.java, resilient/resilient-annotation-processor/src/test/java/ru/tinkoff/kora/resilient/annotation/processor/aop/testdata/CircuitBreakerTarget.java, resilient/resilient-symbol-processor/src/main/kotlin/ru/tinkoff/kora/resilient/symbol/processor/aop/CircuitBreakerKoraAspect.kt, resilient/resilient-symbol-processor/src/test/kotlin/ru/tinkoff/kora/resilient/symbol/processor/aop/CircuitBreakerTests.kt, resilient/resilient-symbol-processor/src/test/kotlin/ru/tinkoff/kora/resilient/symbol/processor/aop/testdata/CircuitBreakerTarget.kt
Features:
- CircuitBreaker void method support fixed
=> Resilient CircuitBreaker Void Method

aop/aop-annotation-processor/src/main/java/ru/tinkoff/kora/aop/annotation/processor/AopProcessor.java, validation/validation-annotation-processor/src/main/java/ru/tinkoff/kora/validation/annotation/processor/aop/ValidateMethodKoraAspect.java, validation/validation-annotation-processor/src/test/java/ru/tinkoff/kora/validation/annotation/processor/ValidAnnotationProcessorTests.java, validation/validation-annotation-processor/src/test/java/ru/tinkoff/kora/validation/annotation/processor/ValidRunner.java, validation/validation-annotation-processor/src/test/java/ru/tinkoff/kora/validation/annotation/processor/ValidateAspectTests.java, validation/validation-annotation-processor/src/test/java/ru/tinkoff/kora/validation/annotation/processor/testdata/ValidFoo.java, validation/validation-annotation-processor/src/test/java/ru/tinkoff/kora/validation/annotation/processor/testdata/ValidateSync.java, validation/validation-common/src/main/java/ru/tinkoff/kora/validation/common/constraint/RangeLongNumberValidator.java, validation/validation-common/src/test/java/ru/tinkoff/kora/validation/common/constraint/ValidationTests.java, validation/validation-symbol-processor/src/main/kotlin/ru/tinkoff/kora/validation/symbol/processor/aop/ValidateMethodKoraAspect.kt, validation/validation-symbol-processor/src/test/kotlin/ru/tinkoff/kora/validation/symbol/processor/ValidateMethodAspectTests.kt
Features:
- Validation argument exception path fixed
- Argument & Return value validation arrayList initial size removed as optimization
=> Validation Argument exception path fixed

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java, openapi/openapi-generator/src/test/java/ru/tinkoff/kora/openapi/generator/KoraCodegenTest.java, openapi/openapi-generator/src/test/resources/example/petstoreV3.yaml
=> Generated models should have primitive types where possible

kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/GraphResolutionHelper.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/KoraAppProcessor.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/KoraAppUtils.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/component/ComponentDependency.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/component/ResolvedComponent.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/declaration/ComponentDeclaration.java, kora-app-annotation-processor/src/test/java/ru/tinkoff/kora/kora/app/annotation/processor/KoraAppProcessorTest.java, kora-app-annotation-processor/src/test/java/ru/tinkoff/kora/kora/app/annotation/processor/KoraBigGraphTest.java, kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/KoraAppProcessor.kt, kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/component/ComponentDependency.kt, kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/component/ResolvedComponent.kt, kora-app-symbol-processor/src/test/kotlin/ru/tinkoff/kora/kora/app/ksp/KoraBigGraphTest.kt
Now application graph initialization and nodes are split in several holder classes with 500 components each.
=> Code too large fix

build.gradle, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinServerApi.mustache
Features:
- kotlinServerApi.mustache incorrect import fixed (closes #164)
=> OpenAPI generation Kotlin Server fixed

http/http-server-annotation-processor/src/main/java/ru/tinkoff/kora/http/server/annotation/processor/RequestHandlerGenerator.java, http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/HttpServerConfig.java, http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/HttpServerModule.java, http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/PrivateApiHandler.java, http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/router/PathTemplate.java, http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/router/PathTemplateMatcher.java, http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/router/PublicApiHandler.java, http/http-server-common/src/test/java/ru/tinkoff/kora/http/server/common/router/PathTemplateMatcherAddTests.java, http/http-server-common/src/test/java/ru/tinkoff/kora/http/server/common/router/PathTemplateMatcherMatchTests.java, http/http-server-common/src/test/java/ru/tinkoff/kora/http/server/common/router/PublicApiHandlerProcessTests.java, http/http-server-common/src/test/java/ru/tinkoff/kora/http/server/common/router/PublicApiHandlerTest.java, http/http-server-common/src/testFixtures/java/ru/tinkoff/kora/http/server/common/HttpServerTestKit.java, http/http-server-symbol-processor/src/main/kotlin/ru/tinkoff/kora/http/server/symbol/procesor/RouteProcessor.kt
Support for trailing slash and non-trailing slash methods generation in single controller fixed
=> HTTP Server trailing slash support

aop/aop-annotation-processor/src/main/java/ru/tinkoff/kora/aop/annotation/processor/AopAnnotationProcessor.java, aop/aop-symbol-processor/src/main/kotlin/ru/tinkoff/kora/aop/symbol/processor/AopSymbolProcessor.kt, json/json-annotation-processor/src/main/java/ru/tinkoff/kora/json/annotation/processor/reader/ReaderTypeMetaParser.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/GraphBuilder.java, kora-app-annotation-processor/src/test/java/ru/tinkoff/kora/kora/app/annotation/processor/DependencyTest.java, kora-app-annotation-processor/src/test/java/ru/tinkoff/kora/kora/app/annotation/processor/KoraAppProcessorTest.java, kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/GraphBuilder.kt, kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/declaration/ComponentDeclaration.kt, kora-app-symbol-processor/src/test/kotlin/ru/tinkoff/kora/kora/app/ksp/KoraAppKspTest.kt
Features:
- Error message improvements
=> Error message improvements

json/json-common/src/main/java/ru/tinkoff/kora/json/common/EnumJsonReader.java
EnumJsonReader error message fixed
=> EnumJsonReader error message fixed

database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/cassandra/CassandraNativeTypes.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/cassandra/CassandraRepositoryGenerator.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/cassandra/extension/CassandraTypesExtension.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/jdbc/JdbcRepositoryGenerator.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/r2dbc/R2dbcRepositoryGenerator.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/vertx/VertxRepositoryGenerator.java, database/database-cassandra/src/main/java/ru/tinkoff/kora/database/cassandra/CassandraModule.java, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/cassandra/CassandraNativeTypes.kt, mkdocs/mkdocs.yml
Features:
- Cassandra module fixes
=> Cassandra module additional date time types support

resilient/resilient-symbol-processor/src/main/kotlin/ru/tinkoff/kora/resilient/symbol/processor/aop/RetryableKoraAspect.kt
Features:
- RetryKoraAspect simplified and value class bug fixed
=> Kotlin Retry Aspect simplified

validation/validation-common/src/main/java/ru/tinkoff/kora/validation/common/constraint/PatternValidator.java, validation/validation-common/src/test/java/ru/tinkoff/kora/validation/common/constraint/ValidationTests.java
Changed search by pattern to check for the whole value
=> PatternValidator should check whole value

json/json-module/src/main/java/ru/tinkoff/kora/json/module/JsonModule.java, json/json-module/src/main/java/ru/tinkoff/kora/json/module/kafka/JsonKafkaDeserializer.java, json/json-module/src/main/java/ru/tinkoff/kora/json/module/kafka/JsonKafkaSerializer.java
=> Json kafka serializer & deserializer
